name: CI/CD Tienda Perritos - Base de Datos

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build y Push de la BD a ECR
      run: |
        docker build -t tienda-db .
        docker tag tienda-db:latest ${{ secrets.ECR_REGISTRY }}/tienda-db:latest
        docker push ${{ secrets.ECR_REGISTRY }}/tienda-db:latest
        
    - name: Actualizar Kubernetes
      run: |
        aws eks update-kubeconfig --name tienda-perritos-cluster-v2 --region us-east-1
        kubectl apply -f mysql-deployment.yaml
